
name: Lint and format java code

on: [push]

env:
  CHECKSTYLE_VERSION: 10.21.3
  GOOGLE_JAVA_FORMAT_VERSION: 1.25.2

defaults:
  run:
    working-directory: backend

jobs:
  lint-java:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            distribution: 'corretto'
            java-version: '11'
        - name: Download Checkstyle
          run: |
            curl -L -o checkstyle-all.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-${{ env.CHECKSTYLE_VERSION }}/checkstyle-${{ env.CHECKSTYLE_VERSION }}-all.jar
        - name: Run Checkstyle
          run: java -jar checkstyle-all.jar -c /google_checks.xml app/src/main/java/

  format-java:
    runs-on: ubuntu-latest
    needs: lint-java
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '8'
      - name: Download Google Java Format
        run: |
          curl -L -o google-java-format.jar https://github.com/google/google-java-format/releases/download/v${{ env.GOOGLE_JAVA_FORMAT_VERSION }}/google-java-format-${{ env.GOOGLE_JAVA_FORMAT_VERSION }}-all-deps.jar
      - name: Run Google Java Format
        run: java -jar google-java-format.jar -r app/src/main/java/**/*.java
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: format Java files"