
name: Lint and format java code

on: [push]

env:
  CHECKSTYLE_VERSION: 10.21.3
  GOOGLE_JAVA_FORMAT_VERSION: 1.25.2

defaults:
  run:
    working-directory: backend

jobs:
  compile-java:
    runs-on: ubuntu-latest
    needs: format-java

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '8'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build

  format-java:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: axel-op/googlejava-format-action@4
        with:
          args: "--aosp --replace"
      - name: Print diffs
        run: git --no-pager diff --exit-code