
name: Lint and format js code

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  format-js:
    runs-on: ubuntu-latest
    needs: lint-js
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: Install Prettier
        run: npm install -g prettier
      - name: Run Prettier
        run: npx prettier --write "**/*.{js,jsx}"
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Code Style Robot - Automated commit"

  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint
