
name: Lint and format java code

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: backend

jobs:
  compile-java:
    runs-on: ubuntu-latest
    needs: format-java

    steps:
      - uses: actions/checkout@v4
        with:
          # If there is a pull request, use the incoming branch commit, otherwise, use the triggering commit
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '8'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build

  format-java:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: axel-op/googlejavaformat-action@v4
        with:
          args: "--aosp --replace"
